apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-lc-angular-14-template
  annotations:
    mia-platform.eu/version: 14.1.0-alpha.0
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: nginx
  labels:
    app: micro-lc-angular-14-template
    app.kubernetes.io/name: micro-lc-angular-14-template
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: em-test
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: dev
    mia-platform.eu/tenant: c1d106ff-4716-49a1-88e2-940b21705986
    mia-platform.eu/log-type: mia-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-lc-angular-14-template
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        mia-platform.eu/version: 14.1.0-alpha.0
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: nginx
      labels:
        app: micro-lc-angular-14-template
        app.kubernetes.io/name: micro-lc-angular-14-template
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: em-test
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: dev
        mia-platform.eu/tenant: c1d106ff-4716-49a1-88e2-940b21705986
        mia-platform.eu/log-type: mia-nginx
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      terminationGracePeriodSeconds: 30
      serviceAccountName: micro-lc-angular-14-template
      containers:
        - name: micro-lc-angular-14-template
          image: nexus.mia-platform.eu/mia-platform-test/micro-lc-angular-14-template
          imagePullPolicy: Always
          resources:
            limits:
              memory: 150Mi
              cpu: 100m
            requests:
              memory: 150Mi
              cpu: 100m
          volumeMounts: []
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args: []
          env:
            - name: HTTP_PORT
              value: '8080'
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/healthz
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes: []
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
